### ISSUE TITLE
Auto update on Raspi

### ISSUE THREAD

**Issue by Phape** [Phape/SpotifyTools#15]
In a previous step, I implemented CI, so that the docker image is built and deployed to ghcr. 
I should now be able to automatically update the version of spotify-tools running on the raspi.

Ideas for implementation:
- Watchtower
- systemd (I already used that)
- Webhooks and github actions (I have already used that as well)

Watchtower:
```yaml
version: '3'
services:
  flask_app:
    image: ghcr.io/<your-github-username>/yourapp:latest
    ports:
      - "80:5000"
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300  # Check every 5 minutes
```

Webhooks:
```yaml
# webhook.py
from flask import Flask, request
import subprocess

app = Flask(__name__)

@app.route('/webhook', methods=['POST'])
def webhook():
    if request.method == 'POST':
        # Pull the latest image and restart the container
        subprocess.run(["docker-compose", "pull"])
        subprocess.run(["docker-compose", "up", "-d"])
        return '', 200

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
```
